//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mbo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_salary_details
    {
        public int id { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<decimal> salaryPaid { get; set; }
        public Nullable<System.DateTime> paidDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
